cantohack/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app_user.urls")),
    path("wallet/", include("wallet.urls")),
    path("portfolio/", include("portfolio.urls")),
    path("", include("contract_generator.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wallet/urls.py
from django.urls import path
from . import views

app_name = "wallet"

urlpatterns = [

	path("canto-wallet/", views.CantoView, name="canto_wallet"),

	path("send-canto-token/<str:token_address>/", views.SendCantoTokenView, name="send_canto_token"),
	
	
	
]

wallet/models.py
from django.db import models

# Create your models here.

wallet/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from app_user.models import AppUser
import requests

# Create your views here.

		

		
@login_required(login_url='/sign-in/')
def CantoView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		pass


	else:
		if app_user.wallet_address == "null":
			resp = requests.post("https://api.iotexchartapp.com/canto-create-wallet/", data={"username": app_user.user}).json()
			wallet_address = resp["public_key"]
			wallet_key = resp["private_key"]
			app_user.wallet_address = wallet_address
			app_user.wallet_key = wallet_key
			app_user.save()
		
		resp = requests.get("https://api.iotexchartapp.com/canto-get-balance/%s" % (app_user.wallet_address)).json()
		data = resp["data"]
		print(data)
		#brise_balance = data[0]["balance"]
		total = 0
		for item in data:
			total += float(item['total_price'])
		context = {"app_user": app_user,  "total": total, "data": data,}
		return render(request, "wallet/canto.html", context )
		
		
@login_required(login_url='/sign-in/')
def SendCantoTokenView(request, token_address):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		sender = app_user.wallet_address
		sender_key = app_user.wallet_key
		receiver = request.POST.get("receiver")
		amount = request.POST.get("amount")
		
		if token_address == "0x826551890dc65655a0aceca109ab11abdbd7a07b":
			token = "wcanto"
		
		elif token_address == "0x4e71a2e537b7f9d9413d3991d37958c0b5e1e503":
			token = "note"
		elif token_address == "0x7264610A66EcA758A8ce95CF11Ff5741E1fd0455":
			token = "cinu"
		
		
		
		
			#name = "Brise"
		else:
			pass
		try:
			resp = requests.post("https://api.iotexchartapp.com/send-canto/", data={"sender":sender,"sender_key":sender_key, "receiver": receiver, "amount":amount, "token":token}).json()
				#SendB(sender, sender_key, receiver, amount, token)
			txn_hash = resp["txn_hash"]
			messages.success(request, (txn_hash))
			return HttpResponseRedirect(reverse("wallet:canto_wallet"))
		except Exception as e:
			messages.warning(request, "Not successfull out of Gas")
				#print e
			return HttpResponseRedirect(reverse("wallet:canto_wallet"))
		
	else:
		resp = requests.get("https://api.iotexchartapp.com/canto-get-balance/%s" % (app_user.wallet_address)).json()
		data = resp["data"]
		if token_address == "0x826551890dc65655a0aceca109ab11abdbd7a07b":
			token = "wcanto"
			token_name = "Cnto"
			brise_balance = data[0]["balance"]
			token_logo = data[0]["logo"]
		
		elif token_address == "0x4e71a2e537b7f9d9413d3991d37958c0b5e1e503":
			token = "note"
			token_name = "Note"
			brise_balance = data[1]["balance"]
			token_logo = data[1]["logo"]
			
		elif token_address == "0x7264610A66EcA758A8ce95CF11Ff5741E1fd0455":
			token = "cinu"
			token_name = "Canto Inu"
			brise_balance = data[2]["balance"]
			token_logo = data[2]["logo"]
		
		
		context = {"app_user": app_user, "token":token, "token_name":token_name, "brise_balance":brise_balance, "token_logo":token_logo, "data":data}
		return render(request, "wallet/send_canto_token.html", context)

def error_404(request, exception):
	return render(request,'app_user/400.html')
	
def error_500(request):
	return render(request,'app_user/500.html')		
		

wallet/templates/wallet/canto.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="uni-connect-wallet uk-section uk-section-large@m uk-panel uk-overflow-hidden uk-border-top">





                <!-- Page header -->
                <header class="uni-page-header">
                    <div class="uk-container">
                    	
                    	<h5  class="uk-h5 uk-h4@m uk-text-center">{{ app_user.user.email }}</h5>
                        
                        <h6 class="heading uk-h3 uk-h6@m uk-text-center">total asset : &dollar;{{ total|floatformat:4|intcomma }}</h6>

                    </div>
                </header>
                <div class="uk-margin-medium-top">
                    <div class="uk-container">
                        <div class="uk-panel uk-flex-column uk-flex-center uk-width-xlarge@m uk-margin-auto">
                            {% if messages %}
                            {% for message in messages %}
                                

                                <!-- Notification bar -->
                                <div class="uk-padding-xsmall uk-text-medium uk-text-bold uk-text-center uk-margin-remove uk-radius-remove uk-background-gradient uk-text-white" data-uk-alert>
                                    <button aria-label="Close" class="uk-alert-close" type="button" data-uk-close></button>
                                    <p class="uk-flex-middle uk-flex-center  uk-margin-remove uk-overflow-hidden"><small>{{ message }} </small></p>
                    
                                </div>    
        
                            {% endfor %}
                            {% endif %}
                            <div class="uk-margin-medium@m" data-uk-margin="margin: uk-margin-xsmall-top">
                            	<p  class="uk-button uk-button-medium uk-width-expand">
                                    <span class="uk-position-center-left uk-position-small"> name - <small>Price</small> </span>
                                    
                                    
                                    <b>balance</b>
                                    <b class="uk-position-center-right uk-position-small">total</b>
                                </p>
                            	{% for item in data %}

                                <a href="{% url 'wallet:send_canto_token' item.token_address %}" class="uk-button uk-button-medium uk-button-default uk-button-outline uk-width-expand">
                                    <span class="uk-position-center-left uk-position-small"> <img class="uk-icon-small" src="{{ item.logo }}" alt="" data-uk-svg loading="lazy"> {{ item.name }} <br><small style="font-size: 10px">${{ item.unit_price|floatformat:4|intcomma }}</small> </span>
                                    <br>
                                    
                                    <b>{{ item.balance|floatformat:4|intcomma }}</b>
                                    <p class="uk-position-center-right uk-position-small">${{ item.total_price|floatformat:4|intcomma }}</p>
                                </a>
                                {% endfor%}

                                <a data-hex="{{ app_user.wallet_address }}"  class="copy-btn uk-button uk-button-primary uk-width-1-1 "><i class="uk-icon-xsmall material-icons">wallet </i> {{ app_user.wallet_address|truncatechars:15 }}</a>
                                <p class="uk-text-center">Click on token to withdraw</p>
                                
                                
                            </div>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

<script type="text/javascript">
  const copyBtns = [...document.getElementsByClassName('copy-btn')]
  let previous = null

  copyBtns.forEach(btn=> btn.addEventListener('click', ()=>{
    const number = btn.getAttribute('data-hex')
    navigator.clipboard.writeText(number)
    btn.textContent = 'address copied to clipboard'

    if (previous) {
      previous.textContent = 'already copied!!'
    }
    previous = btn
  }))
  
  
</script>

<script type="text/javascript">
  const copyBtn = [...document.getElementsByClassName('copy-btns')]
  let previous = null

  copyBtn.forEach(btn=> btn.addEventListener('click', ()=>{
    const number = btn.getAttribute('data-hex')
    navigator.clipboard.writeText(number)
    btn.textContent = 'copied to clipboard'

    if (previous) {
      previous.textContent = 'copied to clipboard'
    }
    previous = btn
  }))
  
  
</script>

{% endblock %}

wallet/templates/wallet/send_canto_token.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="uni-sign-up uk-section uk-section-large@m uk-panel uk-overflow-hidden uk-border-top">

                
                
		
        <!-- Page header -->
                <header class="uni-page-header">
                    <div class="uk-container">
                        <h1 class="heading uk-h3 uk-h3@m uk-text-center">Withdraw</h1>
                        <p class="uk-text-muted uk-margin-remove uk-text-center uk-text-bold">Enter receiver's wallet address to send token</p>
                    </div>
                </header>
                <div class="">
                    <div class="uk-container">
                        <div class="uk-flex-column uk-flex-center uk-width-large@m uk-margin-auto">
                            <form class="uk-form-stacked uk-panel uk-width-1-1" action="" method="post">
                            	{% csrf_token %}
                                <div class="uk-panel uk-inline uk-width-xlarge@m uk-margin-top uk-margin-medium-top@m">
                                        <span class="uk-form-icon">
                                            <img class="uk-icon-small" src="{{ token_logo }}" alt="" data-uk-svg loading="lazy">
                                        </span>
                                        <input type="text" name="receiver" class="uk-input uk-form-large@m uk-radius-large" placeholder="0xAerr33444efk...">
                                        
                                    </div>

                                <div class="form-group uk-panel uk-inline uk-width-large@m uk-margin-top uk-margin-medium-top@m">
                                        
                                        <input type="text" name="amount" class="uk-input uk-form-medium@m uk-radius-large prc">
                                        
                                    </div>
                                
                                <div class="uk-margin uk-grid uk-flex-between uk-flex-middle" data-uk-grid>
                                    <div class="uk-flex uk-flex-middle">
                                        <input id="remember-login-page" type="checkbox" name="remember" class="uk-checkbox">
                                        <label for="remember-login-page" class="uk-form-label uk-margin-xsmall-left">Wallet Balance:{{ brise_balance|floatformat:5|intcomma }}</label>
                                    </div>
                                    <div>
                                        <a href="reset-password.html" class="uk-link-line uk-text-small uk-text-bold">
                                            <span class="fw-600 fs-16">Received Amount:</span><span> <output id="result"></output></span>
                                        </a>
                                    </div>
                                </div>
                                <div class="uk-margin-medium">
                                    <button type="submit" class="uk-button uk-button-primary uk-button-medium@m uk-width-expand">Withdraw token</button>
                                </div>
                                
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

<script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
                                            <script>
                                                $('.form-group').on('input', '.prc', function(){
                                                    var totalSum = 0;
                                                    $('.form-group .prc').each(function() {
                                                        var inputVal = $(this).val();
                                                        if($.isNumeric(inputVal)){
                                                            totalSum += parseFloat(inputVal);
                                                        }
                                                        $('#result').text(totalSum);
                                                    })
                                                });
                                            </script>        

{% endblock %}