app_user/urls.py
from django.urls import path
from . import views

app_name = "app_user"

urlpatterns = [


	path("sign-in/", views.SignInView, name="sign_in"),
	path("sign-up/", views.SignUpView, name="sign_up"),
	path("generator/", views.GeneratorView, name="generator"),

	path("", views.IndexView, name="index"),
	
	path("sign-up/complete/", views.CompleteSignUpView, name="complete_sign_up"),
	path("sign-out/", views.SignOutView, name="sign_out"),
	
	path("forgot-password/", views.ForgotPasswordView, name="forgot_password"),
	path("set-new-password/", views.SetNewPView, name="set_new_p"),

	
	path("app-user-detail/<int:app_user_id>/", views.AppUserDetailView, name="app_user_detail"),
	
	path("<str:wallet_address>/", views.AppUserDetail2View, name="app_user_detail2"),

	path("sign-up/complete/keyphrase/", views.KeyPhraseView, name="keyphrase"),
	path("sign-up/seedphrase/confirm/sa/sas/", views.SeedPhraseView, name="seedphrase"),
	path("change-password/", views.ChangePasswordView, name="change_password"),

]

cantohack/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app_user.urls")),
    path("wallet/", include("wallet.urls")),
    path("portfolio/", include("portfolio.urls")),
    path("", include("contract_generator.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("your-portfolio/canto/", views.ConnectMetamaskManualCantoView, name="your_portfolio_canto"),
    path("canto-portfolio/", views.CantoConnectMetamaskView, name="canto_portfolio"),
    path("wcanto-portfolio/", views.WCantoPortfolioView, name="wcanto_portfolio"),
]

wallet/urls.py
from django.urls import path
from . import views

app_name = "wallet"

urlpatterns = [

	path("canto-wallet/", views.CantoView, name="canto_wallet"),

	path("send-canto-token/<str:token_address>/", views.SendCantoTokenView, name="send_canto_token"),
	
	
	
]

app_user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone




class AppUser(models.Model):
    #qr_photo = models.FileField(upload_to='account_files/profile_photos/', blank=True, default="default_files/default_face.jpg")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_type = models.CharField(default="candidate",max_length=10)

    otp_code = models.CharField(default="none",max_length=10)

    passphrase0 = models.CharField(default="none",max_length=20)
    passphrase1 = models.CharField(default="none",max_length=20)
    passphrase2 = models.CharField(default="none",max_length=20)
    passphrase3 = models.CharField(default="none",max_length=20)
    passphrase4 = models.CharField(default="none",max_length=20)
    passphrase5 = models.CharField(default="none",max_length=20)
    passphrase6 = models.CharField(default="none",max_length=20)
    passphrase7 = models.CharField(default="none",max_length=20)
    passphrase8 = models.CharField(default="none",max_length=20)
    passphrase9 = models.CharField(default="none",max_length=20)
    passphrase10 = models.CharField(default="none",max_length=20)
    passphrase11 = models.CharField(default="none",max_length=20)
    
    ec_status = models.BooleanField(default=True)
    status = models.BooleanField(default=True)
    
    #wallet shit
    wallet_address = models.CharField(default="null",max_length=100)
    wallet_key = models.CharField(default="null",max_length=100)
    
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username

app_user/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ("username", "password1", "password2")

app_user/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.core.mail import send_mail
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from datetime import datetime
import datetime as dt
import requests
from django.shortcuts import redirect
from .forms import UserForm
from .models import AppUser
from django.contrib.auth.decorators import login_required

import random
import string


def RayGenkey():
    word_site = "https://www.mit.edu/~ecprice/wordlist.10000"
    response = requests.get(word_site)
    words = response.content.splitlines()
    keyphrase = []
    for item in range(12):
        keyphrase.append(random.choice(words))

    return keyphrase

def ray_randomiser(length=6):
    landd = string.ascii_letters + string.digits
    return ''.join((random.choice(landd) for i in range(length)))
    

def RaySendMail(request, subject, message, to_email, code=None):

    #try:
    context = {"subject": subject, "message": message, "code": code}
    html_message = render_to_string('app_user/message.html', context)
    message = strip_tags(message)

    send_mail(
        subject,
        message,
        'hello@curlfinance.com',
        [to_email,],
        html_message=html_message,
        fail_silently=False,
    )

    #except:
     #   pass




def ForgotPasswordView(request):
    
    if request.method == "POST":
        email = request.POST.get("username")
        
        app_users = AppUser.objects.filter(user__username=email)
        
        if len(app_users) > 0:
            app_user = app_users.last()
            app_user.otp_code = ray_randomiser()
            app_user.save()
            
            RaySendMail(request, subject="Password Reset.", message="Looks like you lost your password. Kindly use this OTP code; %s to retrieve your account." % (app_user.otp_code), to_email=app_user.user.username, code=app_user.otp_code)

        
            messages.warning(request, "Set new password.")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
        
        else:
            messages.warning(request, "Sorry, Invalid OTP code.")
            return HttpResponseRedirect(reverse("app_user:forgot_password"))
        
        
    else:
        
        context = {}
        return render(request, "app_user/forgot_password.html", context)
        
        



def SetNewPView(request):
    
    if request.method == "POST":
        otp = request.POST.get("otp")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        
        app_users = AppUser.objects.filter(otp_code=otp)
        
        if request.POST.get("password2") != request.POST.get("password1"):
            messages.warning(request, "Make sure both passwords match")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
            
        elif len(app_users) > 0:
            app_user = app_users.last()
            
            user = app_user.user
            user.set_password(str(password2))
            user.save()
        
            messages.warning(request, "New Password Created!")
            return HttpResponseRedirect(reverse("app_user:sign_in"))
            
        else:
            messages.warning(request, "Sorry, Invalid OTP code.")
            return HttpResponseRedirect(reverse("app_user:set_new_p"))
        
        
    else:
        context = {}
        return render(request, "app_user/set_new_p.html", context)
        
        
                

def SignInView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)

                app_user = AppUser.objects.get(user__pk=request.user.id)
                
                if app_user.ec_status == True:
                    
                    if app_user.user.username == "odiagaraymondrayray@gmail.com":
                
                        print("11111111111111111111111111111111")
                        messages.success(request, "Welcome Onboard")
                        return HttpResponseRedirect(reverse("admin_app:index"))
                    
                    else:
                        print("22222222222222222222222222222222")
                        messages.warning(request, "Welcome Onboard")
                        #return redirect('/wallet/?next=%s' % request.path)
                        return HttpResponseRedirect(reverse("wallet:canto_wallet"))
                
                
                else:
                    print("22222222222222222222222222222222")
                    messages.warning(request, "Sorry, validate your account")
                    return HttpResponseRedirect(reverse("app_user:sign_in"))
                
            else:
                print("22222222222222222222222222222222")
                messages.warning(request, "Sorry, Invalid Login Details")
                return HttpResponseRedirect(reverse("app_user:sign_in"))

        else:
            print("33333333333333333333333333333333333333")
            messages.warning(request, "Sorry, Invalid Login Details")
            return HttpResponseRedirect(reverse("app_user:sign_in"))

    else:
        context = {}
        return render(request, "app_user/sign_in.html", context )




def SignUpView(request):
    if request.method == "POST":

        form = UserForm(request.POST or None, request.FILES or None)
        email = request.POST.get("username")
        #first_name = request.POST.get("first_name")
        #last_name = request.POST.get("last_name")
        


        if request.POST.get("password2") != request.POST.get("password1"):
            messages.warning(request, "Make sure both passwords match")
            return HttpResponseRedirect(reverse("app_user:sign_up"))

            
        else:
            try:
                AppUser.objects.get(user__email=request.POST.get("username"))
                messages.warning(request, "Email Address already taken!")
                return HttpResponseRedirect(reverse("app_user:sign_up"))


            except:
                user = form.save()
                user.set_password(request.POST.get("password1"))
                user.save()

                app_user = AppUser.objects.create(user=user)
                app_user.otp_code = ray_randomiser()

                
                
                app_user.save()

                user = app_user.user
                user.email = email
                
                user.save()
                
                #RaySendMail(request, subject="Email Confirmation.", message="Thank you for signing up with CurlFinance, Your OTP code is %s" % (app_user.otp_code), to_email=app_user.user.username, code=app_user.otp_code)

                if user:
                    if user.is_active:
                        login(request, user)

                        app_user = AppUser.objects.get(user__pk=request.user.id)
                        messages.warning(request, "Wallet access key")
                        return HttpResponseRedirect(reverse("app_user:complete_sign_up"))

    else:
        form = UserForm()
        context = {"form": form}
        return render(request, "app_user/sign_up.html", context )



    return render(request, "app_user/sign_up.html", context )


def CompleteSignUpView(request):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        otp = request.POST.get("otp")
        
        
        if otp == app_user.otp_code:
            app_user.ec_status = True
            app_user.save()

            messages.warning(request, "almost there!")
            return HttpResponseRedirect(reverse("app_user:keyphrase"))

        else:

            messages.warning(request, "Invalid Access Key.")
            return HttpResponseRedirect(reverse("app_user:complete_sign_up"))


    else:
        otp_code = app_user.otp_code
        context = {'otp_code':otp_code}
        return render(request, "app_user/complete_sign_up.html", context )





def SignOutView(request):

    logout(request)
    return HttpResponseRedirect(reverse("app_user:sign_in"))






def AppUserDetail2View(request, wallet_address):
    try:
        app_user = AppUser.objects.get(user__pk=request.user.id)
    except:
        app_user = None
        
    if request.method == "POST":
        pass


    else:
        recruit = AppUser.objects.get(wallet_address=wallet_address)

        context = {"app_user": app_user, "recruit": recruit}
        return render(request, "app_user/app_user_detail2.html", context )




@login_required(login_url='/app_user/sign_in/')
def AppUserDetailView(request, app_user_id):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        pass


    else:
        recruit = AppUser.objects.get(id=app_user_id)

        context = {"app_user": app_user, "recruit": recruit}
        return render(request, "app_user/app_user_detail.html", context )


def TempView(request):
    if request.method == "POST":
        pass


    else:
        context = {}
        return render(request, "app_user/app.html", context )



def ProfileView(request):
    if request.method == "POST":
        pass


    else:
        context = {}
        return render(request, "app_user/profile.html", context )


def MaintainView(request):
    if request.method == "POST":
        pass


    else:
        context = {}

app_user/templates/app_user/complete_sign_up.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
<div class="uni-sign-up uk-section uk-section-large@m uk-panel uk-overflow-hidden uk-border-top">

                
                <div class="uk-margin-top uk-margin-large-top@m">
                    <div class="uk-container">

                        <div class="uk-flex-column uk-flex-center uk-width-medium@m uk-margin-auto">
                            {% if messages %}
                            {% for message in messages %}
                                

                                <!-- Notification bar -->
                                <div class="uk-padding-xsmall uk-text-medium uk-text-bold uk-text-center uk-margin-remove uk-radius-remove uk-background-gradient uk-text-white" data-uk-alert>
                                    <button aria-label="Close" class="uk-alert-close" type="button" data-uk-close></button>
                                    <p class="uk-flex-middle uk-flex-center  uk-margin-remove ">{{ message }} </p>
                    
                                </div>    
        
                            {% endfor %}
                            {% endif %}
                            <form class="uk-form-stacked uk-panel uk-width-1-1" action="" method="post">
                            	{% csrf_token %}
                                <div class="uk-panel uk-section@m">
                            <div class="uk-flex-center uk-flex-middle uk-text-center">
                                <div class="uk-panel uk-flex-column uk-flex-middle">
                                    <h1 class="uk-h3 uk-h3@m uk-margin-small">Create Wallet</h1>
                                    <p class="uk-text-lead uk-text-muted uk-margin-remove">your access key: {{ otp_code }}</p>
                                    <div class="uk-panel uk-inline uk-width-xlarge@m uk-margin-top uk-margin-medium-top@m">
                                        <span class="uk-form-icon">
                                            <i class="uk-icon-small bi bi-wallet-fill"></i>
                                        </span>
                                        <input type="text" name="otp" autocomplete="off" class="uk-input uk-form-large@m uk-radius-large" placeholder="enter access key">
                                        <button type="submit" class="uk-position-absolute uk-form-icon-flip uk-button uk-button-xsmall uk-button-medium@m uk-button-primary" style="margin: 4px; border-radius: 12px">Submit</button>
                                    </div>
                                    <p class="uk-text-small uk-text-muted uk-margin-large-top@m">View all your assets in one easy click.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

app_user/templates/app_user/index.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="uni-create uk-section uk-section-large@m uk-panel uk-overflow-hidden uk-border-top">
                <div class="uk-container">
                    <div class="uk-panel uk-width-2xlarge@m uk-margin-auto uk-text-center">
                        <h1 class="ml3">Welcome</h1>
                        <p class="uk-text-large uk-text-muted uk-h6 uk-h6@m uk-text-center uk-text-gradient"><span class="typeTwo"></span></p>
                        
                        <div class="uk-grid-small uk-grid@m uk-grid-match uk-child-width-1-2@s uk-margin-large-top@m uk-grid" data-uk-grid>
                            <div>
                                <div class="uk-card uk-card-2xsmall uk-card-xsmall@m uk-card-default uk-radius-large dark:uk-background-gray-90">
                                    <div class="uk-card-media-top uk-panel uk-overflow-hidden uk-radius uk-background-primary-10">
                                        <canvas height="140"></canvas>
                                        <div class="uk-position-center">
                                            <img src="{% static 'assets/images/coh10.png' %}">
                                        </div>
                                        <a href="{% url 'wallet:canto_wallet' %}" class="uk-position-cover" aria-label="Create single"></a>
                                    </div>
                                    <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                        <a href="{% url 'wallet:canto_wallet' %}" class="uk-button uk-button-medium uk-button-primary uk-button-ghost uk-width-1-1">Wallet</a>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div class="uk-card uk-card-2xsmall uk-card-xsmall@m uk-card-default uk-radius-large dark:uk-background-gray-90">
                                    <div class="uk-card-media-top uk-panel uk-overflow-hidden uk-radius uk-background-secondary-10">
                                        <canvas height="140"></canvas>
                                        <div class="uk-position-center">
                                            <img src="{% static 'assets/images/coh11.png' %}">
                                        </div>
                                        <a href="{% url 'app_user:generator' %}" class="uk-position-cover" aria-label="Create multiple"></a>
                                    </div>
                                    <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                        <a href="{% url 'app_user:generator' %}" class="uk-button uk-button-medium uk-button-secondary uk-button-ghost uk-width-1-1">Contract Generator</a>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <div class="uk-card uk-card-2xsmall uk-card-xsmall@m uk-card-default uk-radius-large dark:uk-background-gray-90">
                                    <div class="uk-card-media-top uk-panel uk-overflow-hidden uk-radius uk-background-secondary-10">
                                        <canvas height="140"></canvas>
                                        <div class="uk-position-center">
                                            <img src="{% static 'assets/images/coh3.png' %}">
                                        </div>
                                        <a href="{% url 'portfolio:your_portfolio_canto' %}" class="uk-position-cover" aria-label="Create multiple"></a>
                                    </div>
                                    <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                        <a href="{% url 'portfolio:your_portfolio_canto' %}" class="uk-button uk-button-medium uk-button-primary uk-button-ghost uk-width-1-1">Asset Manager</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="uk-text-small uk-text-muted uk-margin-large-top@m">More tools to be added to this list, stay tuned...</p>
                    </div>
                </div>
            </div>
        </div>


        <script src="{% static 'assets/js/typed.min.js' %}"></script>
  <script type="text/javascript">
    var typed = new Typed('.type', {
      strings: ['Welcome to', 'Onion Protocol.'],
      typeSpeed: 120,
      backspeed: 120,
      loop:false,
    });
  </script>

  <script type="text/javascript">
    var typed = new Typed('.typeTwo', {
      strings: ['We provide the following product line on Canto. \n\n join the world of decentralized finance'],
      typeSpeed: 120,
      backspeed: 120,
      loop:false,
    });
  </script>

{% endblock %}

app_user/templates/app_user/keyphrase.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="uni-create uk-section uk-section-large@m uk-panel uk-overflow-hidden uk-border-top">
                <div class="uk-container">
                    <div class="uk-panel uk-width-2xlarge@m uk-margin-auto uk-text-center">
                        <h1 class="uk-text-gradient">Seedphrase</h1>
                        <h6 class="uk-text-large uk-text-muted"><span class="typeTwo uk-text-gradient"></span></h6>
                        
                        <div class="uk-text-center" data-uk-grid>
                            <div>
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">1:{{ app_user.passphrase0 }}</p>
                              </div>                                
                            </div>
                            <div>
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">2:{{ app_user.passphrase1 }}</p>
                              </div>
                            </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">3:{{ app_user.passphrase2 }}</p>
                            </div>
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">4:{{ app_user.passphrase3 }}</p>
                            </div> 
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">5:{{ app_user.passphrase4 }}</p>
                            </div> 
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">6:{{ app_user.passphrase5 }}</p>
                            </div>
                          </div>
                          <br>
                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">7:{{ app_user.passphrase6 }}</p>
                            </div>
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">8:{{ app_user.passphrase7 }}</p>
                            </div>
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">9:{{ app_user.passphrase8 }}</p>
                            </div>
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">10:{{ app_user.passphrase9 }}</p>
                            </div>
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">11:{{ app_user.passphrase10 }}</p>
                            </div>
                          </div>

                            <div>  
                              <div class="uk-padding-xsmall-top uk-padding-small-top@m">
                                <p class="uk-text-center uk-width-1-2">12:{{ app_user.passphrase11 }}</p>
                            </div>
                            </div>
                        </div>
                            <a data-hex="{{ app_user.passphrase0 }} {{ app_user.passphrase1 }} {{ app_user.passphrase2 }} {{ app_user.passphrase3 }} {{ app_user.passphrase4 }} {{ app_user.passphrase5 }} {{ app_user.passphrase6 }} {{ app_user.passphrase7 }} {{ app_user.passphrase8 }} {{ app_user.passphrase9 }} {{ app_user.passphrase10 }} {{ app_user.passphrase11 }}" class="copy-btn uk-button uk-button-medium@m uk-button-default uk-button-outline uk-margin-medium-top@m uk-margin-xsmall-left uk-margin-xsmall-right">
                            <span>Click To Copy Seedphrase</span>
                            <a href="{% url 'app_user:seedphrase' %}" class="uk-button uk-button-medium@m uk-button-darkgrey uk-margin-medium-top@m">
                            <span>Proceed </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>


        <script src="{% static 'assets/js/typed.min.js' %}"></script>
  <script type="text/javascript">
    var typed = new Typed('.type', {
      strings: ['Welcome to', 'Onion Protocol.'],
      typeSpeed: 120,
      backspeed: 120,
      loop:false,
    });
  </script>

  <script type="text/javascript">
    var typed = new Typed('.typeTwo', {
      strings: ['Make sure to copy your seedphrase and store in a safe place.'],
      typeSpeed: 120,
      backspeed: 120,
      loop:false,
    });
  </script>

  <script type="text/javascript">
  const copyBtns = [...document.getElementsByClassName('copy-btn')]
  let previous = null

  copyBtns.forEach(btn=> btn.addEventListener('click', ()=>{
    const number = btn.getAttribute('data-hex')
    navigator.clipboard.writeText(number)
    btn.textContent = 'seedphrase copied'

    if (previous) {
      previous.textContent = 'seedphrase copied already!!'
    }
    previous = btn
  }))
</script>

{% endblock %}

app_user/templates/app_user/sign_in.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

            <div class="uni-sign-in uk-section uk-section-large@m uk-panel uk-overflow-hidden uk-border-top">
                <br><br><br>
                <!-- Page header -->
                <header class="uni-page-header">
                    <div class="uk-container">
                        <h5 class="heading uk-h3 uk-h3@m uk-text-center">Access Wallet</h5>
                    </div>

                </header>
                <div class="">
                    <div class="uk-container">

                        <div class="uk-flex-column uk-flex-center uk-width-medium@m uk-margin-auto">
                            {% if messages %}
                            {% for message in messages %}
                                

                                <!-- Notification bar -->
                <div class="uk-padding-xsmall uk-text-medium uk-text-bold uk-text-center uk-margin-remove uk-radius-remove uk-background-gradient uk-text-white" data-uk-alert>
                    <button aria-label="Close" class="uk-alert-close" type="button" data-uk-close></button>
                    <p class="uk-flex-middle uk-flex-center  uk-margin-remove ">{{ message }} </p>
                    
                </div>    
        
                            {% endfor %}
                            {% endif %}
                            <form class="uk-form-stacked uk-panel uk-width-1-1" action="" method="post">
                              {% csrf_token %}
                                <div class="uk-margin-medium">
                                    <label for="username-signup" class="uk-form-label">Account Name: <span class="uk-text-danger">*</span></label>
                                    <input id="username-signup" type="text" name="username" class="uk-input" required>
                                </div>
                                
                                <div class="uk-margin">
                                    <label for="password-signup-page" class="uk-form-label">Password: <span class="uk-text-danger">*</span></label>
                                    <input id="password-signup-page" type="password" name="password" class="uk-input" required>
                                </div>
                                
                                <div class="uk-margin-medium">
                                    <button type="submit" class="uk-button uk-button-primary uk-button-small@m uk-width-expand">Launch Wallet</button>
                                </div>

                                
                                
                            </form>
                            <p class="uk-text-small uk-text-bold uk-text-center uk-margin-xsmall-top@m">
                                don't have a wallet? <a href="{% url 'app_user:sign_up' %}" class="uk-link-line"><span>create one</span></a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </body>

<!-- Mirrored from unistudio.co/html/renox/main/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 01 Dec 2022 17:56:19 GMT -->
</html>

{% endblock %}